name: due
channels:
    - gpytorch
    - pytorch
    - defaults
dependencies:
    - python>=3.6
    - gpytorch=1.5.0
    - pytorch=1.9.0
    - cudatoolkit=10.2
    - torchvision=0.10.0
    - ignite=0.4.4
    - tensorboard
    - tqdm
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
