name: due
channels:
    - gpytorch
    - pytorch
    - defaults
dependencies:
    - python>=3.6
    - gpytorch=1.3.1
    - pytorch=1.7.1
    - torchvision=0.8.2
    - ignite=0.4.2
    - tensorboard
    - tqdm
    - numpy
    - scikit-learn
    - matplotlib
    - seaborn
